### ISSUE TITLE
View energy consumption from a mobile device (Smartphone)

### ISSUE THREAD

**Issue by maddenbr** [cs361-teamLemon/PowerHaus#2]
As a user, I am able to interact with the application from a remote location for ease of access. 

Sub-functionality:
Send consumption data to server: 1 day
Receive specific data from server on mobile application: 2 days
Display data in application: 1 day

**Comment by ElijahCaine** [comment]
We have implemented a web interface over the past few days. The issue uses bootstrap so is mobile ready. This issue is resolved.
